version: "3.8"

services:
  app:
    build: .
    container_name: ecommerce_api_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    container_name: ecommerce_api_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
